from aiohttp import ClientSession
import asyncio
import time
from lxml import etree
import re
import json
song_hash_list = []
import requests
import traceback
import pymongo


urls = [
            "https://www.kugou.com/yy/special/single/19075.html", "https://www.kugou.com/yy/special/single/19503.html",
            "https://www.kugou.com/yy/special/single/24295.html", "https://www.kugou.com/yy/special/single/18506.html",
            "https://www.kugou.com/yy/special/single/18786.html", "https://www.kugou.com/yy/special/single/18998.html",
            "https://www.kugou.com/yy/special/single/19029.html", "https://www.kugou.com/yy/special/single/18260.html",
            "https://www.kugou.com/yy/special/single/19563.html", "https://www.kugou.com/yy/special/single/19017.html",
            "https://www.kugou.com/yy/special/single/19787.html", "https://www.kugou.com/yy/special/single/325145.html",
            "https://www.kugou.com/yy/special/single/508418.html",
            "https://www.kugou.com/yy/special/single/123857.html",
            "https://www.kugou.com/yy/special/single/520554.html",
            "https://www.kugou.com/yy/special/single/372977.html",
            "https://www.kugou.com/yy/special/single/528964.html",
            "https://www.kugou.com/yy/special/single/545321.html",
            "https://www.kugou.com/yy/special/single/204156.html",
            "https://www.kugou.com/yy/special/single/390708.html",
            "https://www.kugou.com/yy/special/single/549445.html",
            "https://www.kugou.com/yy/special/single/524508.html",
            "https://www.kugou.com/yy/special/single/561965.html",
            "https://www.kugou.com/yy/special/single/238737.html",
            "https://www.kugou.com/yy/special/single/283622.html", "https://www.kugou.com/yy/special/single/58722.html",
            "https://www.kugou.com/yy/special/single/513096.html",
            "https://www.kugou.com/yy/special/single/525968.html",
            "https://www.kugou.com/yy/special/single/425909.html",
            "https://www.kugou.com/yy/special/single/126912.html",
            "https://www.kugou.com/yy/special/single/426131.html",
            "https://www.kugou.com/yy/special/single/486441.html",
            "https://www.kugou.com/yy/special/single/568173.html",
            "https://www.kugou.com/yy/special/single/541854.html",
            "https://www.kugou.com/yy/special/single/128325.html",
            "https://www.kugou.com/yy/special/single/574316.html",
            "https://www.kugou.com/yy/special/single/129993.html",
            "https://www.kugou.com/yy/special/single/129989.html",
            "https://www.kugou.com/yy/special/single/378247.html",
            "https://www.kugou.com/yy/special/single/545913.html",
            "https://www.kugou.com/yy/special/single/553560.html",
            "https://www.kugou.com/yy/special/single/123933.html",
            "https://www.kugou.com/yy/special/single/376683.html",
            "https://www.kugou.com/yy/special/single/147090.html",
            "https://www.kugou.com/yy/special/single/566912.html",
            "https://www.kugou.com/yy/special/single/126741.html",
            "https://www.kugou.com/yy/special/single/128299.html",
            "https://www.kugou.com/yy/special/single/360017.html",
            "https://www.kugou.com/yy/special/single/405100.html",
            "https://www.kugou.com/yy/special/single/419782.html",
            "https://www.kugou.com/yy/special/single/158974.html",
            "https://www.kugou.com/yy/special/single/409546.html", "https://www.kugou.com/yy/special/single/18772.html",
            "https://www.kugou.com/yy/special/single/362991.html",
            "https://www.kugou.com/yy/special/single/574312.html",
            "https://www.kugou.com/yy/special/single/449776.html",
            "https://www.kugou.com/yy/special/single/157197.html",
            "https://www.kugou.com/yy/special/single/175980.html",
            "https://www.kugou.com/yy/special/single/419786.html",
            "https://www.kugou.com/yy/special/single/403569.html",
            "https://www.kugou.com/yy/special/single/189399.html",
            "https://www.kugou.com/yy/special/single/227208.html",
            "https://www.kugou.com/yy/special/single/126542.html", "https://www.kugou.com/yy/special/single/19630.html",
            "https://www.kugou.com/yy/special/single/157548.html",
            "https://www.kugou.com/yy/special/single/569409.html",
            "https://www.kugou.com/yy/special/single/369654.html",
            "https://www.kugou.com/yy/special/single/202231.html",
            "https://www.kugou.com/yy/special/single/525799.html",
            "https://www.kugou.com/yy/special/single/341305.html",
            "https://www.kugou.com/yy/special/single/277599.html",
            "https://www.kugou.com/yy/special/single/421504.html",
            "https://www.kugou.com/yy/special/single/125709.html",
            "https://www.kugou.com/yy/special/single/446416.html",
            "https://www.kugou.com/yy/special/single/394486.html",
            "https://www.kugou.com/yy/special/single/402993.html",
            "https://www.kugou.com/yy/special/single/580393.html",
            "https://www.kugou.com/yy/special/single/139684.html",
            "https://www.kugou.com/yy/special/single/334209.html",
            "https://www.kugou.com/yy/special/single/191005.html",
            "https://www.kugou.com/yy/special/single/503541.html",
            "https://www.kugou.com/yy/special/single/360976.html", "https://www.kugou.com/yy/special/single/21877.html",
            "https://www.kugou.com/yy/special/single/409553.html",
            "https://www.kugou.com/yy/special/single/327653.html",
            "https://www.kugou.com/yy/special/single/567662.html",
            "https://www.kugou.com/yy/special/single/562983.html",
            "https://www.kugou.com/yy/special/single/579316.html",
            "https://www.kugou.com/yy/special/single/173661.html",
            "https://www.kugou.com/yy/special/single/154110.html",
            "https://www.kugou.com/yy/special/single/397647.html",
            "https://www.kugou.com/yy/special/single/547455.html",
            "https://www.kugou.com/yy/special/single/404751.html",
            "https://www.kugou.com/yy/special/single/397801.html",
            "https://www.kugou.com/yy/special/single/173904.html",
            "https://www.kugou.com/yy/special/single/403000.html",
            "https://www.kugou.com/yy/special/single/530141.html",
            "https://www.kugou.com/yy/special/single/329461.html",
            "https://www.kugou.com/yy/special/single/145609.html", "https://www.kugou.com/yy/special/single/22519.html",
            "https://www.kugou.com/yy/special/single/570668.html",
            "https://www.kugou.com/yy/special/single/123129.html",
            "https://www.kugou.com/yy/special/single/566272.html",
            "https://www.kugou.com/yy/special/single/574192.html",
            "https://www.kugou.com/yy/special/single/132022.html",
            "https://www.kugou.com/yy/special/single/123399.html",
            "https://www.kugou.com/yy/special/single/551164.html",
            "https://www.kugou.com/yy/special/single/159228.html",
            "https://www.kugou.com/yy/special/single/418031.html",
            "https://www.kugou.com/yy/special/single/574655.html",
            "https://www.kugou.com/yy/special/single/394492.html",
            "https://www.kugou.com/yy/special/single/557206.html",
            "https://www.kugou.com/yy/special/single/529575.html",
            "https://www.kugou.com/yy/special/single/417588.html",
            "https://www.kugou.com/yy/special/single/579842.html",
            "https://www.kugou.com/yy/special/single/123368.html",
            "https://www.kugou.com/yy/special/single/576283.html",
            "https://www.kugou.com/yy/special/single/371240.html",
            "https://www.kugou.com/yy/special/single/580597.html",
            "https://www.kugou.com/yy/special/single/173997.html",
            "https://www.kugou.com/yy/special/single/123205.html",
            "https://www.kugou.com/yy/special/single/533746.html",
            "https://www.kugou.com/yy/special/single/548993.html", "https://www.kugou.com/yy/special/single/20509.html",
            "https://www.kugou.com/yy/special/single/525690.html",
            "https://www.kugou.com/yy/special/single/573932.html",
            "https://www.kugou.com/yy/special/single/133655.html",
            "https://www.kugou.com/yy/special/single/222385.html",
            "https://www.kugou.com/yy/special/single/538919.html", "https://www.kugou.com/yy/special/single/19274.html",
            "https://www.kugou.com/yy/special/single/18350.html", "https://www.kugou.com/yy/special/single/126846.html",
            "https://www.kugou.com/yy/special/single/359212.html",
            "https://www.kugou.com/yy/special/single/238133.html",
            "https://www.kugou.com/yy/special/single/222011.html",
            "https://www.kugou.com/yy/special/single/555986.html",
            "https://www.kugou.com/yy/special/single/282229.html",
            "https://www.kugou.com/yy/special/single/402859.html",
            "https://www.kugou.com/yy/special/single/209228.html",
            "https://www.kugou.com/yy/special/single/565160.html",
            "https://www.kugou.com/yy/special/single/122899.html",
            "https://www.kugou.com/yy/special/single/123390.html",
            "https://www.kugou.com/yy/special/single/198126.html",
            "https://www.kugou.com/yy/special/single/513846.html",
            "https://www.kugou.com/yy/special/single/395832.html",
            "https://www.kugou.com/yy/special/single/363831.html",
            "https://www.kugou.com/yy/special/single/318934.html",
            "https://www.kugou.com/yy/special/single/116590.html",
            "https://www.kugou.com/yy/special/single/514845.html",
            "https://www.kugou.com/yy/special/single/126845.html",
            "https://www.kugou.com/yy/special/single/200346.html",
            "https://www.kugou.com/yy/special/single/126340.html",
            "https://www.kugou.com/yy/special/single/127783.html",
            "https://www.kugou.com/yy/special/single/568332.html", "https://www.kugou.com/yy/special/single/19818.html",
            "https://www.kugou.com/yy/special/single/527155.html",
            "https://www.kugou.com/yy/special/single/122401.html",
            "https://www.kugou.com/yy/special/single/550732.html",
            "https://www.kugou.com/yy/special/single/408936.html", "https://www.kugou.com/yy/special/single/18459.html",
            "https://www.kugou.com/yy/special/single/126821.html",
            "https://www.kugou.com/yy/special/single/411379.html",
            "https://www.kugou.com/yy/special/single/125821.html",
            "https://www.kugou.com/yy/special/single/125440.html",
            "https://www.kugou.com/yy/special/single/552771.html", "https://www.kugou.com/yy/special/single/19338.html",
            "https://www.kugou.com/yy/special/single/206331.html",
            "https://www.kugou.com/yy/special/single/363536.html",
            "https://www.kugou.com/yy/special/single/272903.html",
            "https://www.kugou.com/yy/special/single/384486.html",
            "https://www.kugou.com/yy/special/single/560522.html",
            "https://www.kugou.com/yy/special/single/284434.html",
            "https://www.kugou.com/yy/special/single/128350.html",
            "https://www.kugou.com/yy/special/single/567412.html",
            "https://www.kugou.com/yy/special/single/225893.html",
            "https://www.kugou.com/yy/special/single/241920.html",
            "https://www.kugou.com/yy/special/single/122814.html",
            "https://www.kugou.com/yy/special/single/558372.html",
            "https://www.kugou.com/yy/special/single/128195.html",
            "https://www.kugou.com/yy/special/single/360369.html",
            "https://www.kugou.com/yy/special/single/418034.html",
            "https://www.kugou.com/yy/special/single/418580.html",
            "https://www.kugou.com/yy/special/single/122992.html",
            "https://www.kugou.com/yy/special/single/122258.html",
            "https://www.kugou.com/yy/special/single/568860.html",
            "https://www.kugou.com/yy/special/single/255625.html", "https://www.kugou.com/yy/special/single/56680.html",
            "https://www.kugou.com/yy/special/single/125847.html",
            "https://www.kugou.com/yy/special/single/308600.html",
            "https://www.kugou.com/yy/special/single/282523.html",
            "https://www.kugou.com/yy/special/single/302074.html",
            "https://www.kugou.com/yy/special/single/254826.html",
            "https://www.kugou.com/yy/special/single/133999.html",
            "https://www.kugou.com/yy/special/single/570912.html",
            "https://www.kugou.com/yy/special/single/122834.html",
            "https://www.kugou.com/yy/special/single/205056.html", "https://www.kugou.com/yy/special/single/19728.html",
            "https://www.kugou.com/yy/special/single/576282.html",
            "https://www.kugou.com/yy/special/single/418442.html", "https://www.kugou.com/yy/special/single/22228.html",
            "https://www.kugou.com/yy/special/single/123331.html",
            "https://www.kugou.com/yy/special/single/125456.html",
            "https://www.kugou.com/yy/special/single/502835.html",
            "https://www.kugou.com/yy/special/single/147361.html",
            "https://www.kugou.com/yy/special/single/397703.html",
            "https://www.kugou.com/yy/special/single/122780.html",
            "https://www.kugou.com/yy/special/single/169028.html",
            "https://www.kugou.com/yy/special/single/269951.html",
            "https://www.kugou.com/yy/special/single/289852.html",
            "https://www.kugou.com/yy/special/single/534036.html", "https://www.kugou.com/yy/special/single/18969.html",
            "https://www.kugou.com/yy/special/single/419219.html",
            "https://www.kugou.com/yy/special/single/570033.html",
            "https://www.kugou.com/yy/special/single/276433.html",
            "https://www.kugou.com/yy/special/single/388848.html",
            "https://www.kugou.com/yy/special/single/123540.html",
            "https://www.kugou.com/yy/special/single/132790.html",
            "https://www.kugou.com/yy/special/single/125346.html",
            "https://www.kugou.com/yy/special/single/123568.html",
            "https://www.kugou.com/yy/special/single/280442.html",
            "https://www.kugou.com/yy/special/single/362855.html",
            "https://www.kugou.com/yy/special/single/122557.html",
            "https://www.kugou.com/yy/special/single/124961.html",
            "https://www.kugou.com/yy/special/single/380253.html",
            "https://www.kugou.com/yy/special/single/150224.html",
            "https://www.kugou.com/yy/special/single/534149.html",
            "https://www.kugou.com/yy/special/single/122214.html",
            "https://www.kugou.com/yy/special/single/170663.html",
            "https://www.kugou.com/yy/special/single/126844.html", "https://www.kugou.com/yy/special/single/57310.html",
            "https://www.kugou.com/yy/special/single/3251.html", "https://www.kugou.com/yy/special/single/552969.html",
            "https://www.kugou.com/yy/special/single/533462.html",
            "https://www.kugou.com/yy/special/single/538675.html",
            "https://www.kugou.com/yy/special/single/354158.html",
            "https://www.kugou.com/yy/special/single/232223.html", "https://www.kugou.com/yy/special/single/18476.html",
            "https://www.kugou.com/yy/special/single/408905.html",
            "https://www.kugou.com/yy/special/single/426339.html", "https://www.kugou.com/yy/special/single/18562.html",
            "https://www.kugou.com/yy/special/single/217585.html",
            "https://www.kugou.com/yy/special/single/122464.html",
            "https://www.kugou.com/yy/special/single/550437.html",
            "https://www.kugou.com/yy/special/single/122686.html",
            "https://www.kugou.com/yy/special/single/121827.html",
            "https://www.kugou.com/yy/special/single/581634.html",
            "https://www.kugou.com/yy/special/single/122269.html",
            "https://www.kugou.com/yy/special/single/317959.html",
            "https://www.kugou.com/yy/special/single/178880.html",
            "https://www.kugou.com/yy/special/single/123800.html",
            "https://www.kugou.com/yy/special/single/123215.html",
            "https://www.kugou.com/yy/special/single/123304.html",
            "https://www.kugou.com/yy/special/single/315868.html", "https://www.kugou.com/yy/special/single/22233.html",
            "https://www.kugou.com/yy/special/single/214520.html",
            "https://www.kugou.com/yy/special/single/164262.html",
            "https://www.kugou.com/yy/special/single/534744.html",
            "https://www.kugou.com/yy/special/single/157373.html",
            "https://www.kugou.com/yy/special/single/447392.html",
            "https://www.kugou.com/yy/special/single/510986.html",
            "https://www.kugou.com/yy/special/single/397663.html",
            "https://www.kugou.com/yy/special/single/123492.html",
            "https://www.kugou.com/yy/special/single/144500.html",
            "https://www.kugou.com/yy/special/single/502838.html",
            "https://www.kugou.com/yy/special/single/125175.html",
            "https://www.kugou.com/yy/special/single/537986.html",
            "https://www.kugou.com/yy/special/single/376658.html",
            "https://www.kugou.com/yy/special/single/123018.html", "https://www.kugou.com/yy/special/single/20082.html",
            "https://www.kugou.com/yy/special/single/535173.html",
            "https://www.kugou.com/yy/special/single/123308.html", "https://www.kugou.com/yy/special/single/19306.html",
            "https://www.kugou.com/yy/special/single/122390.html",
            "https://www.kugou.com/yy/special/single/556506.html", "https://www.kugou.com/yy/special/single/57292.html",
            "https://www.kugou.com/yy/special/single/18931.html", "https://www.kugou.com/yy/special/single/125178.html",
            "https://www.kugou.com/yy/special/single/122987.html",
            "https://www.kugou.com/yy/special/single/164277.html",
            "https://www.kugou.com/yy/special/single/477543.html",
            "https://www.kugou.com/yy/special/single/433687.html",
            "https://www.kugou.com/yy/special/single/397364.html", "https://www.kugou.com/yy/special/single/56524.html",
            "https://www.kugou.com/yy/special/single/172684.html",
            "https://www.kugou.com/yy/special/single/124237.html", "https://www.kugou.com/yy/special/single/7911.html",
            "https://www.kugou.com/yy/special/single/503262.html",
            "https://www.kugou.com/yy/special/single/274929.html",
            "https://www.kugou.com/yy/special/single/122669.html",
            "https://www.kugou.com/yy/special/single/553311.html",
            "https://www.kugou.com/yy/special/single/571050.html",
            "https://www.kugou.com/yy/special/single/168350.html",
            "https://www.kugou.com/yy/special/single/127433.html",
            "https://www.kugou.com/yy/special/single/397684.html",
            "https://www.kugou.com/yy/special/single/371720.html",
            "https://www.kugou.com/yy/special/single/126290.html",
            "https://www.kugou.com/yy/special/single/571361.html",
            "https://www.kugou.com/yy/special/single/471221.html",
            "https://www.kugou.com/yy/special/single/187043.html",
            "https://www.kugou.com/yy/special/single/166643.html",
            "https://www.kugou.com/yy/special/single/126094.html",
            "https://www.kugou.com/yy/special/single/123468.html",
            "https://www.kugou.com/yy/special/single/392311.html",
            "https://www.kugou.com/yy/special/single/563318.html",
            "https://www.kugou.com/yy/special/single/568684.html", "https://www.kugou.com/yy/special/single/8870.html",
            "https://www.kugou.com/yy/special/single/562433.html",
            "https://www.kugou.com/yy/special/single/418847.html",
            "https://www.kugou.com/yy/special/single/132791.html", "https://www.kugou.com/yy/special/single/10175.html",
            "https://www.kugou.com/yy/special/single/555885.html", "https://www.kugou.com/yy/special/single/18816.html",
            "https://www.kugou.com/yy/special/single/19405.html", "https://www.kugou.com/yy/special/single/18690.html",
            "https://www.kugou.com/yy/special/single/534196.html",
            "https://www.kugou.com/yy/special/single/163021.html",
            "https://www.kugou.com/yy/special/single/469998.html", "https://www.kugou.com/yy/special/single/3066.html",
            "https://www.kugou.com/yy/special/single/360325.html",
            "https://www.kugou.com/yy/special/single/465815.html",
            "https://www.kugou.com/yy/special/single/136723.html",
            "https://www.kugou.com/yy/special/single/499590.html",
            "https://www.kugou.com/yy/special/single/473322.html",
            "https://www.kugou.com/yy/special/single/142705.html",
            "https://www.kugou.com/yy/special/single/125708.html",
            "https://www.kugou.com/yy/special/single/519935.html",
            "https://www.kugou.com/yy/special/single/139449.html",
            "https://www.kugou.com/yy/special/single/127718.html",
            "https://www.kugou.com/yy/special/single/464008.html",
            "https://www.kugou.com/yy/special/single/182793.html",
            "https://www.kugou.com/yy/special/single/200164.html",
            "https://www.kugou.com/yy/special/single/556706.html",
            "https://www.kugou.com/yy/special/single/474449.html",
            "https://www.kugou.com/yy/special/single/540349.html",
            "https://www.kugou.com/yy/special/single/136577.html",
            "https://www.kugou.com/yy/special/single/128371.html",
            "https://www.kugou.com/yy/special/single/380622.html",
            "https://www.kugou.com/yy/special/single/212117.html",
            "https://www.kugou.com/yy/special/single/137580.html",
            "https://www.kugou.com/yy/special/single/349305.html",
            "https://www.kugou.com/yy/special/single/194880.html", "https://www.kugou.com/yy/special/single/19266.html",
            "https://www.kugou.com/yy/special/single/133133.html",
            "https://www.kugou.com/yy/special/single/126285.html",
            "https://www.kugou.com/yy/special/single/122585.html",
            "https://www.kugou.com/yy/special/single/543550.html",
            "https://www.kugou.com/yy/special/single/230138.html",
            "https://www.kugou.com/yy/special/single/563169.html",
            "https://www.kugou.com/yy/special/single/479782.html",
            "https://www.kugou.com/yy/special/single/123446.html",
            "https://www.kugou.com/yy/special/single/216566.html",
            "https://www.kugou.com/yy/special/single/124461.html",
            "https://www.kugou.com/yy/special/single/555869.html", "https://www.kugou.com/yy/special/single/18179.html",
            "https://www.kugou.com/yy/special/single/490357.html",
            "https://www.kugou.com/yy/special/single/122103.html",
            "https://www.kugou.com/yy/special/single/123576.html",
            "https://www.kugou.com/yy/special/single/270578.html",
            "https://www.kugou.com/yy/special/single/157112.html",
            "https://www.kugou.com/yy/special/single/125040.html",
            "https://www.kugou.com/yy/special/single/189137.html",
            "https://www.kugou.com/yy/special/single/500132.html",
            "https://www.kugou.com/yy/special/single/144505.html",
            "https://www.kugou.com/yy/special/single/195391.html",
            "https://www.kugou.com/yy/special/single/123131.html",
            "https://www.kugou.com/yy/special/single/207393.html",
            "https://www.kugou.com/yy/special/single/178546.html",
            "https://www.kugou.com/yy/special/single/132322.html",
            "https://www.kugou.com/yy/special/single/352823.html", "https://www.kugou.com/yy/special/single/18502.html",
            "https://www.kugou.com/yy/special/single/478497.html",
            "https://www.kugou.com/yy/special/single/343332.html",
            "https://www.kugou.com/yy/special/single/387592.html",
            "https://www.kugou.com/yy/special/single/306844.html",
            "https://www.kugou.com/yy/special/single/426531.html",
            "https://www.kugou.com/yy/special/single/136192.html",
            "https://www.kugou.com/yy/special/single/439859.html",
            "https://www.kugou.com/yy/special/single/190416.html",
            "https://www.kugou.com/yy/special/single/545611.html",
            "https://www.kugou.com/yy/special/single/128959.html",
            "https://www.kugou.com/yy/special/single/482341.html",
            "https://www.kugou.com/yy/special/single/122121.html",
            "https://www.kugou.com/yy/special/single/124044.html",
            "https://www.kugou.com/yy/special/single/153207.html",
            "https://www.kugou.com/yy/special/single/122264.html",
            "https://www.kugou.com/yy/special/single/274028.html",
            "https://www.kugou.com/yy/special/single/127990.html",
            "https://www.kugou.com/yy/special/single/149730.html",
            "https://www.kugou.com/yy/special/single/568980.html", "https://www.kugou.com/yy/special/single/17907.html",
            "https://www.kugou.com/yy/special/single/369585.html",
            "https://www.kugou.com/yy/special/single/358365.html",
            "https://www.kugou.com/yy/special/single/123628.html",
            "https://www.kugou.com/yy/special/single/146412.html",
            "https://www.kugou.com/yy/special/single/157140.html",
            "https://www.kugou.com/yy/special/single/561188.html",
            "https://www.kugou.com/yy/special/single/387007.html",
            "https://www.kugou.com/yy/special/single/189493.html",
            "https://www.kugou.com/yy/special/single/357767.html",
            "https://www.kugou.com/yy/special/single/352189.html",
            "https://www.kugou.com/yy/special/single/546031.html",
            "https://www.kugou.com/yy/special/single/126544.html",
            "https://www.kugou.com/yy/special/single/199436.html",
            "https://www.kugou.com/yy/special/single/303614.html",
            "https://www.kugou.com/yy/special/single/225961.html",
            "https://www.kugou.com/yy/special/single/547014.html",
            "https://www.kugou.com/yy/special/single/223454.html",
            "https://www.kugou.com/yy/special/single/128375.html",
            "https://www.kugou.com/yy/special/single/127677.html",
            "https://www.kugou.com/yy/special/single/317557.html", "https://www.kugou.com/yy/special/single/17962.html",
            "https://www.kugou.com/yy/special/single/272053.html",
            "https://www.kugou.com/yy/special/single/390034.html",
            "https://www.kugou.com/yy/special/single/450164.html",
            "https://www.kugou.com/yy/special/single/123127.html",
            "https://www.kugou.com/yy/special/single/490254.html",
            "https://www.kugou.com/yy/special/single/189063.html",
            "https://www.kugou.com/yy/special/single/230949.html",
            "https://www.kugou.com/yy/special/single/334134.html", "https://www.kugou.com/yy/special/single/18854.html",
            "https://www.kugou.com/yy/special/single/118716.html",
            "https://www.kugou.com/yy/special/single/168361.html",
            "https://www.kugou.com/yy/special/single/221129.html", "https://www.kugou.com/yy/special/single/22273.html",
            "https://www.kugou.com/yy/special/single/18993.html", "https://www.kugou.com/yy/special/single/547000.html",
            "https://www.kugou.com/yy/special/single/559728.html",
            "https://www.kugou.com/yy/special/single/155040.html", "https://www.kugou.com/yy/special/single/18873.html",
            "https://www.kugou.com/yy/special/single/124272.html",
            "https://www.kugou.com/yy/special/single/491402.html", "https://www.kugou.com/yy/special/single/20965.html",
            "https://www.kugou.com/yy/special/single/19225.html", "https://www.kugou.com/yy/special/single/9686.html",
            "https://www.kugou.com/yy/special/single/141879.html", "https://www.kugou.com/yy/special/single/26166.html",
            "https://www.kugou.com/yy/special/single/128381.html",
            "https://www.kugou.com/yy/special/single/236732.html",
            "https://www.kugou.com/yy/special/single/124230.html",
            "https://www.kugou.com/yy/special/single/127871.html",
            "https://www.kugou.com/yy/special/single/126420.html", "https://www.kugou.com/yy/special/single/14813.html",
            "https://www.kugou.com/yy/special/single/122725.html",
            "https://www.kugou.com/yy/special/single/343179.html",
            "https://www.kugou.com/yy/special/single/576216.html",
            "https://www.kugou.com/yy/special/single/167787.html",
            "https://www.kugou.com/yy/special/single/173033.html",
            "https://www.kugou.com/yy/special/single/378212.html", "https://www.kugou.com/yy/special/single/19107.html",
            "https://www.kugou.com/yy/special/single/238760.html",
            "https://www.kugou.com/yy/special/single/192351.html", "https://www.kugou.com/yy/special/single/4414.html",
            "https://www.kugou.com/yy/special/single/424363.html", "https://www.kugou.com/yy/special/single/4266.html",
            "https://www.kugou.com/yy/special/single/473252.html",
            "https://www.kugou.com/yy/special/single/534059.html",
            "https://www.kugou.com/yy/special/single/570974.html",
            "https://www.kugou.com/yy/special/single/127070.html", "https://www.kugou.com/yy/special/single/4960.html",
            "https://www.kugou.com/yy/special/single/123214.html",
            "https://www.kugou.com/yy/special/single/392375.html",
            "https://www.kugou.com/yy/special/single/385567.html",
            "https://www.kugou.com/yy/special/single/306616.html",
            "https://www.kugou.com/yy/special/single/404377.html",
            "https://www.kugou.com/yy/special/single/133574.html",
            "https://www.kugou.com/yy/special/single/403064.html",
            "https://www.kugou.com/yy/special/single/227253.html", "https://www.kugou.com/yy/special/single/38640.html",
            "https://www.kugou.com/yy/special/single/558704.html",
            "https://www.kugou.com/yy/special/single/128893.html", "https://www.kugou.com/yy/special/single/5772.html",
            "https://www.kugou.com/yy/special/single/325778.html", "https://www.kugou.com/yy/special/single/18767.html",
            "https://www.kugou.com/yy/special/single/538928.html",
            "https://www.kugou.com/yy/special/single/144286.html",
            "https://www.kugou.com/yy/special/single/355023.html",
            "https://www.kugou.com/yy/special/single/230931.html", "https://www.kugou.com/yy/special/single/22300.html",
            "https://www.kugou.com/yy/special/single/128528.html",
            "https://www.kugou.com/yy/special/single/238147.html", "https://www.kugou.com/yy/special/single/19409.html",
            "https://www.kugou.com/yy/special/single/123452.html",
            "https://www.kugou.com/yy/special/single/144265.html",
            "https://www.kugou.com/yy/special/single/584600.html",
            "https://www.kugou.com/yy/special/single/356959.html", "https://www.kugou.com/yy/special/single/18759.html",
            "https://www.kugou.com/yy/special/single/564609.html",
            "https://www.kugou.com/yy/special/single/548707.html",
            "https://www.kugou.com/yy/special/single/147059.html",
            "https://www.kugou.com/yy/special/single/404656.html", "https://www.kugou.com/yy/special/single/20603.html",
            "https://www.kugou.com/yy/special/single/564568.html", "https://www.kugou.com/yy/special/single/8462.html",
            "https://www.kugou.com/yy/special/single/209215.html", "https://www.kugou.com/yy/special/single/18315.html",
            "https://www.kugou.com/yy/special/single/499048.html",
            "https://www.kugou.com/yy/special/single/478817.html",
            "https://www.kugou.com/yy/special/single/127129.html",
            "https://www.kugou.com/yy/special/single/126226.html",
            "https://www.kugou.com/yy/special/single/107737.html",
            "https://www.kugou.com/yy/special/single/417114.html",
            "https://www.kugou.com/yy/special/single/144847.html",
            "https://www.kugou.com/yy/special/single/125392.html",
            "https://www.kugou.com/yy/special/single/228503.html",
            "https://www.kugou.com/yy/special/single/170702.html",
            "https://www.kugou.com/yy/special/single/399846.html",
            "https://www.kugou.com/yy/special/single/127983.html",
            "https://www.kugou.com/yy/special/single/545777.html", "https://www.kugou.com/yy/special/single/20033.html",
            "https://www.kugou.com/yy/special/single/390033.html", "https://www.kugou.com/yy/special/single/25633.html",
            "https://www.kugou.com/yy/special/single/125520.html", "https://www.kugou.com/yy/special/single/56407.html",
            "https://www.kugou.com/yy/special/single/147539.html",
            "https://www.kugou.com/yy/special/single/204767.html",
            "https://www.kugou.com/yy/special/single/136001.html",
            "https://www.kugou.com/yy/special/single/123858.html", "https://www.kugou.com/yy/special/single/19458.html",
            "https://www.kugou.com/yy/special/single/130079.html",
            "https://www.kugou.com/yy/special/single/384456.html",
            "https://www.kugou.com/yy/special/single/131621.html",
            "https://www.kugou.com/yy/special/single/539074.html",
            "https://www.kugou.com/yy/special/single/123514.html",
            "https://www.kugou.com/yy/special/single/315675.html",
            "https://www.kugou.com/yy/special/single/376203.html", "https://www.kugou.com/yy/special/single/18625.html",
            "https://www.kugou.com/yy/special/single/20003.html", "https://www.kugou.com/yy/special/single/18096.html",
            "https://www.kugou.com/yy/special/single/163827.html",
            "https://www.kugou.com/yy/special/single/440384.html", "https://www.kugou.com/yy/special/single/18332.html",
            "https://www.kugou.com/yy/special/single/494986.html",
            "https://www.kugou.com/yy/special/single/470020.html", "https://www.kugou.com/yy/special/single/20842.html",
            "https://www.kugou.com/yy/special/single/386012.html",
            "https://www.kugou.com/yy/special/single/529071.html", "https://www.kugou.com/yy/special/single/18958.html",
            "https://www.kugou.com/yy/special/single/113063.html", "https://www.kugou.com/yy/special/single/18946.html",
            "https://www.kugou.com/yy/special/single/123198.html",
            "https://www.kugou.com/yy/special/single/131902.html",
            "https://www.kugou.com/yy/special/single/484416.html",
            "https://www.kugou.com/yy/special/single/567746.html",
            "https://www.kugou.com/yy/special/single/525645.html",
            "https://www.kugou.com/yy/special/single/370206.html",
            "https://www.kugou.com/yy/special/single/126430.html", "https://www.kugou.com/yy/special/single/23562.html",
            "https://www.kugou.com/yy/special/single/374761.html",
            "https://www.kugou.com/yy/special/single/305700.html",
            "https://www.kugou.com/yy/special/single/126419.html",
            "https://www.kugou.com/yy/special/single/299355.html",
            "https://www.kugou.com/yy/special/single/438560.html", "https://www.kugou.com/yy/special/single/19476.html",
            "https://www.kugou.com/yy/special/single/25986.html", "https://www.kugou.com/yy/special/single/167949.html",
            "https://www.kugou.com/yy/special/single/191457.html",
            "https://www.kugou.com/yy/special/single/379915.html",
            "https://www.kugou.com/yy/special/single/343391.html",
            "https://www.kugou.com/yy/special/single/582070.html", "https://www.kugou.com/yy/special/single/56723.html",
            "https://www.kugou.com/yy/special/single/26083.html", "https://www.kugou.com/yy/special/single/281862.html",
            "https://www.kugou.com/yy/special/single/126789.html",
            "https://www.kugou.com/yy/special/single/573449.html",
            "https://www.kugou.com/yy/special/single/409350.html",
            "https://www.kugou.com/yy/special/single/123307.html",
            "https://www.kugou.com/yy/special/single/419712.html",
            "https://www.kugou.com/yy/special/single/207400.html",
            "https://www.kugou.com/yy/special/single/304782.html",
            "https://www.kugou.com/yy/special/single/200127.html",
            "https://www.kugou.com/yy/special/single/502938.html",
            "https://www.kugou.com/yy/special/single/126724.html", "https://www.kugou.com/yy/special/single/20422.html",
            "https://www.kugou.com/yy/special/single/555275.html",
            "https://www.kugou.com/yy/special/single/387302.html",
            "https://www.kugou.com/yy/special/single/570678.html", "https://www.kugou.com/yy/special/single/26200.html",
            "https://www.kugou.com/yy/special/single/383334.html",
            "https://www.kugou.com/yy/special/single/231373.html", "https://www.kugou.com/yy/special/single/19470.html",
            "https://www.kugou.com/yy/special/single/178868.html", "https://www.kugou.com/yy/special/single/24258.html",
            "https://www.kugou.com/yy/special/single/454758.html",
            "https://www.kugou.com/yy/special/single/545532.html",
            "https://www.kugou.com/yy/special/single/270746.html",
            "https://www.kugou.com/yy/special/single/381442.html",
            "https://www.kugou.com/yy/special/single/501211.html",
            "https://www.kugou.com/yy/special/single/134336.html", "https://www.kugou.com/yy/special/single/55860.html",
            "https://www.kugou.com/yy/special/single/547023.html",
            "https://www.kugou.com/yy/special/single/533732.html",
            "https://www.kugou.com/yy/special/single/525625.html", "https://www.kugou.com/yy/special/single/18519.html",
            "https://www.kugou.com/yy/special/single/31253.html", "https://www.kugou.com/yy/special/single/19403.html",
            "https://www.kugou.com/yy/special/single/575866.html",
            "https://www.kugou.com/yy/special/single/347103.html",
            "https://www.kugou.com/yy/special/single/195408.html",
            "https://www.kugou.com/yy/special/single/181709.html",
            "https://www.kugou.com/yy/special/single/197736.html",
            "https://www.kugou.com/yy/special/single/340140.html",
            "https://www.kugou.com/yy/special/single/425914.html",
            "https://www.kugou.com/yy/special/single/126728.html",
            "https://www.kugou.com/yy/special/single/575088.html",
            "https://www.kugou.com/yy/special/single/158860.html",
            "https://www.kugou.com/yy/special/single/136187.html",
            "https://www.kugou.com/yy/special/single/163795.html",
            "https://www.kugou.com/yy/special/single/453339.html",
            "https://www.kugou.com/yy/special/single/512153.html",
            "https://www.kugou.com/yy/special/single/491893.html", "https://www.kugou.com/yy/special/single/18475.html",
            "https://www.kugou.com/yy/special/single/18606.html", "https://www.kugou.com/yy/special/single/126417.html",
            "https://www.kugou.com/yy/special/single/19840.html", "https://www.kugou.com/yy/special/single/411189.html",
            "https://www.kugou.com/yy/special/single/536770.html",
            "https://www.kugou.com/yy/special/single/126423.html",
            "https://www.kugou.com/yy/special/single/193173.html",
            "https://www.kugou.com/yy/special/single/267923.html",
            "https://www.kugou.com/yy/special/single/367307.html",
            "https://www.kugou.com/yy/special/single/119452.html",
            "https://www.kugou.com/yy/special/single/577634.html",
            "https://www.kugou.com/yy/special/single/222352.html",
            "https://www.kugou.com/yy/special/single/159247.html",
            "https://www.kugou.com/yy/special/single/357359.html",
            "https://www.kugou.com/yy/special/single/343011.html",
            "https://www.kugou.com/yy/special/single/434823.html",
            "https://www.kugou.com/yy/special/single/401617.html",
            "https://www.kugou.com/yy/special/single/316028.html",
            "https://www.kugou.com/yy/special/single/159654.html", "https://www.kugou.com/yy/special/single/5902.html",
            "https://www.kugou.com/yy/special/single/24748.html", "https://www.kugou.com/yy/special/single/125792.html",
            "https://www.kugou.com/yy/special/single/458285.html", "https://www.kugou.com/yy/special/single/4492.html",
            "https://www.kugou.com/yy/special/single/341730.html",
            "https://www.kugou.com/yy/special/single/386293.html",
            "https://www.kugou.com/yy/special/single/482997.html",
            "https://www.kugou.com/yy/special/single/584602.html",
            "https://www.kugou.com/yy/special/single/129617.html", "https://www.kugou.com/yy/special/single/18994.html",
            "https://www.kugou.com/yy/special/single/560346.html",
            "https://www.kugou.com/yy/special/single/385847.html", "https://www.kugou.com/yy/special/single/2369.html",
            "https://www.kugou.com/yy/special/single/387414.html",
            "https://www.kugou.com/yy/special/single/207416.html",
            "https://www.kugou.com/yy/special/single/526338.html", "https://www.kugou.com/yy/special/single/19531.html",
            "https://www.kugou.com/yy/special/single/188762.html",
            "https://www.kugou.com/yy/special/single/164676.html",
            "https://www.kugou.com/yy/special/single/513263.html",
            "https://www.kugou.com/yy/special/single/426362.html", "https://www.kugou.com/yy/special/single/264.html",
            "https://www.kugou.com/yy/special/single/190654.html",
            "https://www.kugou.com/yy/special/single/536584.html", "https://www.kugou.com/yy/special/single/17989.html",
            "https://www.kugou.com/yy/special/single/151606.html",
            "https://www.kugou.com/yy/special/single/546347.html",
            "https://www.kugou.com/yy/special/single/195399.html", "https://www.kugou.com/yy/special/single/4988.html",
            "https://www.kugou.com/yy/special/single/212872.html",
            "https://www.kugou.com/yy/special/single/419709.html",
            "https://www.kugou.com/yy/special/single/354938.html",
            "https://www.kugou.com/yy/special/single/122578.html",
            "https://www.kugou.com/yy/special/single/190619.html",
            "https://www.kugou.com/yy/special/single/220725.html",
            "https://www.kugou.com/yy/special/single/464244.html",
            "https://www.kugou.com/yy/special/single/533198.html",
            "https://www.kugou.com/yy/special/single/585230.html",
            "https://www.kugou.com/yy/special/single/281854.html", "https://www.kugou.com/yy/special/single/7104.html",
            "https://www.kugou.com/yy/special/single/157807.html",
            "https://www.kugou.com/yy/special/single/401491.html",
            "https://www.kugou.com/yy/special/single/181080.html",
            "https://www.kugou.com/yy/special/single/157151.html", "https://www.kugou.com/yy/special/single/21206.html",
            "https://www.kugou.com/yy/special/single/21860.html", "https://www.kugou.com/yy/special/single/574324.html",
            "https://www.kugou.com/yy/special/single/19250.html", "https://www.kugou.com/yy/special/single/19234.html",
            "https://www.kugou.com/yy/special/single/383164.html",
            "https://www.kugou.com/yy/special/single/517511.html",
            "https://www.kugou.com/yy/special/single/530765.html",
            "https://www.kugou.com/yy/special/single/582742.html", "https://www.kugou.com/yy/special/single/19374.html",
            "https://www.kugou.com/yy/special/single/142883.html",
            "https://www.kugou.com/yy/special/single/279024.html",
            "https://www.kugou.com/yy/special/single/352160.html",
            "https://www.kugou.com/yy/special/single/115528.html", "https://www.kugou.com/yy/special/single/23365.html",
            "https://www.kugou.com/yy/special/single/507392.html",
            "https://www.kugou.com/yy/special/single/281944.html",
            "https://www.kugou.com/yy/special/single/125736.html",
            "https://www.kugou.com/yy/special/single/238495.html",
            "https://www.kugou.com/yy/special/single/122678.html",
            "https://www.kugou.com/yy/special/single/172752.html",
            "https://www.kugou.com/yy/special/single/356470.html", "https://www.kugou.com/yy/special/single/24150.html",
            "https://www.kugou.com/yy/special/single/146187.html",
            "https://www.kugou.com/yy/special/single/369400.html",
            "https://www.kugou.com/yy/special/single/410505.html", "https://www.kugou.com/yy/special/single/7328.html",
            "https://www.kugou.com/yy/special/single/387065.html", "https://www.kugou.com/yy/special/single/21464.html",
            "https://www.kugou.com/yy/special/single/193812.html",
            "https://www.kugou.com/yy/special/single/454104.html", "https://www.kugou.com/yy/special/single/20317.html",
            "https://www.kugou.com/yy/special/single/139094.html",
            "https://www.kugou.com/yy/special/single/214444.html", "https://www.kugou.com/yy/special/single/19486.html",
            "https://www.kugou.com/yy/special/single/375507.html",
            "https://www.kugou.com/yy/special/single/355340.html",
            "https://www.kugou.com/yy/special/single/347605.html",
            "https://www.kugou.com/yy/special/single/519431.html", "https://www.kugou.com/yy/special/single/19087.html",
            "https://www.kugou.com/yy/special/single/379390.html", "https://www.kugou.com/yy/special/single/72720.html",
            "https://www.kugou.com/yy/special/single/382531.html",
            "https://www.kugou.com/yy/special/single/505417.html",
            "https://www.kugou.com/yy/special/single/486316.html",
            "https://www.kugou.com/yy/special/single/123987.html",
            "https://www.kugou.com/yy/special/single/369059.html",
            "https://www.kugou.com/yy/special/single/281868.html", "https://www.kugou.com/yy/special/single/15401.html",
            "https://www.kugou.com/yy/special/single/574458.html",
            "https://www.kugou.com/yy/special/single/158659.html", "https://www.kugou.com/yy/special/single/40111.html",
            "https://www.kugou.com/yy/special/single/19271.html", "https://www.kugou.com/yy/special/single/346713.html",
            "https://www.kugou.com/yy/special/single/165371.html", "https://www.kugou.com/yy/special/single/18245.html",
            "https://www.kugou.com/yy/special/single/500129.html",
            "https://www.kugou.com/yy/special/single/302588.html",
            "https://www.kugou.com/yy/special/single/405120.html",
            "https://www.kugou.com/yy/special/single/415751.html",
            "https://www.kugou.com/yy/special/single/353159.html",
            "https://www.kugou.com/yy/special/single/213989.html", "https://www.kugou.com/yy/special/single/20316.html",
            "https://www.kugou.com/yy/special/single/21111.html", "https://www.kugou.com/yy/special/single/163545.html",
            "https://www.kugou.com/yy/special/single/9084.html", "https://www.kugou.com/yy/special/single/192890.html",
            "https://www.kugou.com/yy/special/single/520763.html",
            "https://www.kugou.com/yy/special/single/138276.html",
            "https://www.kugou.com/yy/special/single/263107.html",
            "https://www.kugou.com/yy/special/single/333943.html",
            "https://www.kugou.com/yy/special/single/240325.html",
            "https://www.kugou.com/yy/special/single/547787.html",
            "https://www.kugou.com/yy/special/single/348979.html",
            "https://www.kugou.com/yy/special/single/479609.html",
            "https://www.kugou.com/yy/special/single/174984.html", "https://www.kugou.com/yy/special/single/19154.html",
            "https://www.kugou.com/yy/special/single/262814.html",
            "https://www.kugou.com/yy/special/single/383465.html",
            "https://www.kugou.com/yy/special/single/191076.html",
            "https://www.kugou.com/yy/special/single/127828.html",
            "https://www.kugou.com/yy/special/single/358345.html",
            "https://www.kugou.com/yy/special/single/183007.html",
            "https://www.kugou.com/yy/special/single/561818.html",
            "https://www.kugou.com/yy/special/single/456122.html", "https://www.kugou.com/yy/special/single/23334.html",
            "https://www.kugou.com/yy/special/single/140548.html",
            "https://www.kugou.com/yy/special/single/378446.html",
            "https://www.kugou.com/yy/special/single/161012.html",
            "https://www.kugou.com/yy/special/single/366051.html",
            "https://www.kugou.com/yy/special/single/419091.html",
            "https://www.kugou.com/yy/special/single/351858.html",
            "https://www.kugou.com/yy/special/single/429608.html",
            "https://www.kugou.com/yy/special/single/161688.html",
            "https://www.kugou.com/yy/special/single/238641.html",
            "https://www.kugou.com/yy/special/single/535804.html",
            "https://www.kugou.com/yy/special/single/421347.html",
            "https://www.kugou.com/yy/special/single/307359.html",
            "https://www.kugou.com/yy/special/single/146547.html",
            "https://www.kugou.com/yy/special/single/208467.html", "https://www.kugou.com/yy/special/single/56652.html",
            "https://www.kugou.com/yy/special/single/18833.html", "https://www.kugou.com/yy/special/single/439762.html",
            "https://www.kugou.com/yy/special/single/290286.html",
            "https://www.kugou.com/yy/special/single/405127.html",
            "https://www.kugou.com/yy/special/single/503082.html",
            "https://www.kugou.com/yy/special/single/501871.html",
            "https://www.kugou.com/yy/special/single/161129.html",
            "https://www.kugou.com/yy/special/single/303311.html",
            "https://www.kugou.com/yy/special/single/463546.html", "https://www.kugou.com/yy/special/single/23392.html",
            "https://www.kugou.com/yy/special/single/546259.html",
            "https://www.kugou.com/yy/special/single/261999.html",
            "https://www.kugou.com/yy/special/single/365392.html",
            "https://www.kugou.com/yy/special/single/518305.html",
            "https://www.kugou.com/yy/special/single/393734.html",
            "https://www.kugou.com/yy/special/single/370222.html", "https://www.kugou.com/yy/special/single/19528.html",
            "https://www.kugou.com/yy/special/single/571703.html",
            "https://www.kugou.com/yy/special/single/253584.html",
            "https://www.kugou.com/yy/special/single/274736.html",
            "https://www.kugou.com/yy/special/single/401631.html",
            "https://www.kugou.com/yy/special/single/204614.html", "https://www.kugou.com/yy/special/single/23870.html",
            "https://www.kugou.com/yy/special/single/220446.html", "https://www.kugou.com/yy/special/single/9980.html",
            "https://www.kugou.com/yy/special/single/147424.html",
            "https://www.kugou.com/yy/special/single/279282.html", "https://www.kugou.com/yy/special/single/298.html",
            "https://www.kugou.com/yy/special/single/321992.html",
            "https://www.kugou.com/yy/special/single/583607.html",
            "https://www.kugou.com/yy/special/single/316082.html",
            "https://www.kugou.com/yy/special/single/535439.html",
            "https://www.kugou.com/yy/special/single/302301.html",
            "https://www.kugou.com/yy/special/single/448665.html",
            "https://www.kugou.com/yy/special/single/367313.html",
            "https://www.kugou.com/yy/special/single/519093.html",
            "https://www.kugou.com/yy/special/single/501144.html",
            "https://www.kugou.com/yy/special/single/163025.html", "https://www.kugou.com/yy/special/single/9206.html",
            "https://www.kugou.com/yy/special/single/546344.html", "https://www.kugou.com/yy/special/single/18264.html",
            "https://www.kugou.com/yy/special/single/382748.html",
            "https://www.kugou.com/yy/special/single/342972.html",
            "https://www.kugou.com/yy/special/single/447367.html",
            "https://www.kugou.com/yy/special/single/352150.html",
            "https://www.kugou.com/yy/special/single/189019.html",
            "https://www.kugou.com/yy/special/single/156196.html",
            "https://www.kugou.com/yy/special/single/501049.html",
            "https://www.kugou.com/yy/special/single/549423.html",
            "https://www.kugou.com/yy/special/single/385862.html",
            "https://www.kugou.com/yy/special/single/356150.html",
            "https://www.kugou.com/yy/special/single/279278.html",
            "https://www.kugou.com/yy/special/single/335182.html",
            "https://www.kugou.com/yy/special/single/382807.html",
            "https://www.kugou.com/yy/special/single/383278.html", "https://www.kugou.com/yy/special/single/2955.html",
            "https://www.kugou.com/yy/special/single/156157.html",
            "https://www.kugou.com/yy/special/single/281875.html",
            "https://www.kugou.com/yy/special/single/472780.html",
            "https://www.kugou.com/yy/special/single/378898.html", "https://www.kugou.com/yy/special/single/11145.html",
            "https://www.kugou.com/yy/special/single/548003.html", "https://www.kugou.com/yy/special/single/18684.html",
            "https://www.kugou.com/yy/special/single/498990.html",
            "https://www.kugou.com/yy/special/single/163030.html",
            "https://www.kugou.com/yy/special/single/223456.html",
            "https://www.kugou.com/yy/special/single/581346.html",
            "https://www.kugou.com/yy/special/single/275834.html",
            "https://www.kugou.com/yy/special/single/169577.html", "https://www.kugou.com/yy/special/single/19537.html",
            "https://www.kugou.com/yy/special/single/279495.html",
            "https://www.kugou.com/yy/special/single/445803.html",
            "https://www.kugou.com/yy/special/single/275806.html",
            "https://www.kugou.com/yy/special/single/403805.html",
            "https://www.kugou.com/yy/special/single/144391.html",
            "https://www.kugou.com/yy/special/single/368168.html",
            "https://www.kugou.com/yy/special/single/397269.html",
            "https://www.kugou.com/yy/special/single/454373.html",
            "https://www.kugou.com/yy/special/single/550555.html", "https://www.kugou.com/yy/special/single/4976.html",
            "https://www.kugou.com/yy/special/single/3952.html", "https://www.kugou.com/yy/special/single/535828.html",
            "https://www.kugou.com/yy/special/single/125077.html",
            "https://www.kugou.com/yy/special/single/396625.html",
            "https://www.kugou.com/yy/special/single/387787.html",
            "https://www.kugou.com/yy/special/single/355652.html",
            "https://www.kugou.com/yy/special/single/147027.html",
            "https://www.kugou.com/yy/special/single/479688.html",
            "https://www.kugou.com/yy/special/single/351925.html", "https://www.kugou.com/yy/special/single/25520.html",
            "https://www.kugou.com/yy/special/single/18446.html", "https://www.kugou.com/yy/special/single/174977.html",
            "https://www.kugou.com/yy/special/single/518293.html",
            "https://www.kugou.com/yy/special/single/284715.html",
            "https://www.kugou.com/yy/special/single/150335.html",
            "https://www.kugou.com/yy/special/single/437071.html",
            "https://www.kugou.com/yy/special/single/171923.html",
            "https://www.kugou.com/yy/special/single/141480.html",
            "https://www.kugou.com/yy/special/single/413456.html",
            "https://www.kugou.com/yy/special/single/411723.html",
            "https://www.kugou.com/yy/special/single/547384.html",
            "https://www.kugou.com/yy/special/single/534636.html",
            "https://www.kugou.com/yy/special/single/418598.html",
            "https://www.kugou.com/yy/special/single/204235.html", "https://www.kugou.com/yy/special/single/19779.html",
            "https://www.kugou.com/yy/special/single/136788.html",
            "https://www.kugou.com/yy/special/single/365119.html",
            "https://www.kugou.com/yy/special/single/202247.html",
            "https://www.kugou.com/yy/special/single/497954.html",
            "https://www.kugou.com/yy/special/single/371913.html",
            "https://www.kugou.com/yy/special/single/139737.html",
            "https://www.kugou.com/yy/special/single/475571.html",
            "https://www.kugou.com/yy/special/single/460317.html",
            "https://www.kugou.com/yy/special/single/222488.html",
            "https://www.kugou.com/yy/special/single/463968.html",
            "https://www.kugou.com/yy/special/single/561806.html",
            "https://www.kugou.com/yy/special/single/506173.html",
            "https://www.kugou.com/yy/special/single/450386.html",
            "https://www.kugou.com/yy/special/single/383658.html",
            "https://www.kugou.com/yy/special/single/427787.html",
            "https://www.kugou.com/yy/special/single/453341.html", "https://www.kugou.com/yy/special/single/56795.html",
            "https://www.kugou.com/yy/special/single/246687.html",
            "https://www.kugou.com/yy/special/single/395020.html",
            "https://www.kugou.com/yy/special/single/239989.html",
            "https://www.kugou.com/yy/special/single/518469.html",
            "https://www.kugou.com/yy/special/single/371925.html",
            "https://www.kugou.com/yy/special/single/556304.html",
            "https://www.kugou.com/yy/special/single/376313.html",
            "https://www.kugou.com/yy/special/single/283486.html",
            "https://www.kugou.com/yy/special/single/437631.html", "https://www.kugou.com/yy/special/single/13967.html",
            "https://www.kugou.com/yy/special/single/171706.html",
            "https://www.kugou.com/yy/special/single/143278.html",
            "https://www.kugou.com/yy/special/single/459671.html",
            "https://www.kugou.com/yy/special/single/389946.html",
            "https://www.kugou.com/yy/special/single/201478.html", "https://www.kugou.com/yy/special/single/18412.html",
            "https://www.kugou.com/yy/special/single/173635.html", "https://www.kugou.com/yy/special/single/19681.html",
            "https://www.kugou.com/yy/special/single/155208.html",
            "https://www.kugou.com/yy/special/single/268270.html",
            "https://www.kugou.com/yy/special/single/214667.html",
            "https://www.kugou.com/yy/special/single/411724.html",
            "https://www.kugou.com/yy/special/single/490552.html",
            "https://www.kugou.com/yy/special/single/442816.html",
            "https://www.kugou.com/yy/special/single/434415.html",
            "https://www.kugou.com/yy/special/single/563130.html",
            "https://www.kugou.com/yy/special/single/367879.html",
            "https://www.kugou.com/yy/special/single/188069.html",
            "https://www.kugou.com/yy/special/single/184567.html",
            "https://www.kugou.com/yy/special/single/393478.html",
            "https://www.kugou.com/yy/special/single/126776.html",
            "https://www.kugou.com/yy/special/single/129140.html",
            "https://www.kugou.com/yy/special/single/334607.html",
            "https://www.kugou.com/yy/special/single/211184.html",
            "https://www.kugou.com/yy/special/single/300023.html", "https://www.kugou.com/yy/special/single/21113.html",
            "https://www.kugou.com/yy/special/single/19183.html", "https://www.kugou.com/yy/special/single/344617.html",
            "https://www.kugou.com/yy/special/single/365298.html",
            "https://www.kugou.com/yy/special/single/161480.html",
            "https://www.kugou.com/yy/special/single/232766.html",
            "https://www.kugou.com/yy/special/single/412712.html",
            "https://www.kugou.com/yy/special/single/448659.html",
            "https://www.kugou.com/yy/special/single/340791.html", "https://www.kugou.com/yy/special/single/19584.html",
            "https://www.kugou.com/yy/special/single/536714.html",
            "https://www.kugou.com/yy/special/single/345238.html",
            "https://www.kugou.com/yy/special/single/359323.html",
            "https://www.kugou.com/yy/special/single/197054.html",
            "https://www.kugou.com/yy/special/single/393741.html",
            "https://www.kugou.com/yy/special/single/2804.html",
            "https://www.kugou.com/yy/special/single/546278.html",
            "https://www.kugou.com/yy/special/single/438151.html",
            "https://www.kugou.com/yy/special/single/130686.html",
            "https://www.kugou.com/yy/special/single/180848.html",
            "https://www.kugou.com/yy/special/single/273893.html",
            "https://www.kugou.com/yy/special/single/158934.html",
            "https://www.kugou.com/yy/special/single/240760.html",
            "https://www.kugou.com/yy/special/single/266350.html",
            "https://www.kugou.com/yy/special/single/166752.html",
            "https://www.kugou.com/yy/special/single/549109.html",
            "https://www.kugou.com/yy/special/single/457951.html",
            "https://www.kugou.com/yy/special/single/129701.html",
            "https://www.kugou.com/yy/special/single/224159.html",
            "https://www.kugou.com/yy/special/single/19510.html",
            "https://www.kugou.com/yy/special/single/11144.html", "https://www.kugou.com/yy/special/single/398517.html",
            "https://www.kugou.com/yy/special/single/27417.html", "https://www.kugou.com/yy/special/single/18996.html",
            "https://www.kugou.com/yy/special/single/285255.html",
            "https://www.kugou.com/yy/special/single/161342.html",
            "https://www.kugou.com/yy/special/single/129568.html",
            "https://www.kugou.com/yy/special/single/203219.html",
            "https://www.kugou.com/yy/special/single/150050.html",
            "https://www.kugou.com/yy/special/single/250998.html",
            "https://www.kugou.com/yy/special/single/213259.html",
            "https://www.kugou.com/yy/special/single/265997.html",
            "https://www.kugou.com/yy/special/single/420059.html",
            "https://www.kugou.com/yy/special/single/395602.html",
            "https://www.kugou.com/yy/special/single/352167.html",
            "https://www.kugou.com/yy/special/single/308028.html",
            "https://www.kugou.com/yy/special/single/495245.html",
            "https://www.kugou.com/yy/special/single/281635.html", "https://www.kugou.com/yy/special/single/26199.html",
            "https://www.kugou.com/yy/special/single/530267.html", "https://www.kugou.com/yy/special/single/23473.html",
            "https://www.kugou.com/yy/special/single/126497.html",
            "https://www.kugou.com/yy/special/single/448663.html", "https://www.kugou.com/yy/special/single/19359.html",
            "https://www.kugou.com/yy/special/single/5194.html", "https://www.kugou.com/yy/special/single/255770.html",
            "https://www.kugou.com/yy/special/single/431419.html",
            "https://www.kugou.com/yy/special/single/199185.html", "https://www.kugou.com/yy/special/single/9513.html",
            "https://www.kugou.com/yy/special/single/436719.html",
            "https://www.kugou.com/yy/special/single/351201.html",
            "https://www.kugou.com/yy/special/single/390587.html",
            "https://www.kugou.com/yy/special/single/227998.html",
            "https://www.kugou.com/yy/special/single/322034.html",
            "https://www.kugou.com/yy/special/single/448661.html",
            "https://www.kugou.com/yy/special/single/328676.html", "https://www.kugou.com/yy/special/single/371933.html"
        ]
headers = {"User-Agent":"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.78 Safari/537.36"}
uri = "mongodb://kugou_admin:Xiaoxian0910@localhost:27017"
client = pymongo.MongoClient(uri)
db = client['kugou']
collection = db['kugoump3']

async def GetSong(session):
    for url_2 in urls:
        # url_2 = "https://www.kugou.com/yy/special/single/{}.html".format(id)
        try:
            async with session.get(url_2, headers=headers) as response:
                response = await response.text()
                selector = etree.HTML(response)
                results = selector.xpath('//*[@class="dq"]/following::*')
                for result in results:
                    try:
                        song_hash = re.search(r'\w*', str(result.attrib['data'])).group()
                        song_hash_list.append(song_hash)
                    except:
                        pass
        except:
            print(traceback.format_exc())
            print(url_2)
        for song_hash in song_hash_list:
            url = "https://wwwapi.kugou.com/yy/index.php?r=play/getdata&callback&hash={}".format(song_hash)
            async with session.get(url,headers=headers) as response:
                response = await response.read()
                response_json = json.loads(response.decode('utf-8'))
                img = response_json.get('data').get('img')
                mp3 = response_json.get('data').get('play_url')
                song_title = response_json.get('data').get('audio_name')
                song_lyrics = response_json.get('data').get('lyrics')
                record = {'name': song_title, 'link': mp3, 'lyrics': song_lyrics, 'img': img}
                print("Writing {}".format(song_title))
                collection.insert(record)
                # print(song_title,"  ",mp3)
                # data = song_title + "#" + mp3 + "\n"
                # with open("/Users/u44084750/Desktop/mp3/url.txt", 'a') as f:
                #     f.write(data)

        # try:
        #
        #         song = requests.get(mp3,headers=headers).content
        #         f_obj = open(r'/Users/u44084750/Desktop/mp3/{}.mp3'.format(song_title),'wb')
        #         f_lyrics = open(r'/Users/u44084750/Desktop/mp3/{}.lrc'.format(song_title), 'w')
        #         print("Downloading {}".format(song_title))
        #         f_obj.write(song)
        #         f_obj.close()
        #         f_lyrics.write(song_lyrics)
        #         f_lyrics.close()
        #     except:
        #         pass


async def GetResource(loop):
    # global song_title
    async with ClientSession() as session:
        # for main_url in urls:
        #     async with session.get(main_url,headers=headers) as response:
        #         response = await response.read()
        #         response_json = json.loads(response.decode('utf-8'))
        #         for i in range(len(response_json.get('data').get('lists'))):
        #             id = response_json.get('data').get('lists')[i].get('specialid')
                    tasks = []
                    task = asyncio.ensure_future(GetSong(session))
                    tasks.append(task)
                    await asyncio.gather(*tasks)










start_time = time.time()
loop = asyncio.get_event_loop()
loop.run_until_complete(GetResource(loop))
loop.close()
end_time = time.time()
print(end_time-start_time)